"""Add email sending tracker column

Revision ID: bcd4186db196
Revises: bd98b382b35c
Create Date: 2025-07-12 12:25:56.639412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd4186db196'
down_revision: Union[str, Sequence[str], None] = 'bd98b382b35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_email_triggered_at', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_email_triggered_at')
    # ### end Alembic commands ###
